### ISSUE TITLE
Digital RF 2.6.3 cmake issue

### ISSUE THREAD

**Issue by tdgedenk** [MITHaystack/digital_rf#6]
When trying to upgrade to the latest version of drf I encounter when running the _**cmake ..**_ command. Attached is a picture of my terminal. 

![drf_cmake_error](https://user-images.githubusercontent.com/52427082/68338896-632db880-00db-11ea-920a-2bd8f911e6f8.png)

**Comment by ryanvolz** [comment]
This *is* due to the recent change, but it actually worked fine and is only a warning. This happens because it tries to find Python using a module that is only available on very recent versions of CMake; if it fails, it falls back to what it has done before. I will have to think about silencing the warning in some way so as not to alarm people.

**Comment by ryanvolz** [comment]
Quieted the warning with commit bbd9ad9.
